#docker run --network "${PWD##*/}_app-tier" -v "$(pwd):/artifacts" godatadriven/pyspark --driver-class-path /artifacts/utils/postgresql-42.2.12.jar --jars /artifacts/utils/postgresql-42.2.12.jar /artifacts/Entry_Point.py
#docker exec -it <container> psql -d my_database -U my_user

version: '2'

networks:
  app-tier:
    driver: bridge

services:

  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql-server
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=Change123
      - POSTGRESQL_DATABASE=my_database
    networks:
      - app-tier
#
#  pyspark:
#    image: 'godatadriven/pyspark'
#    container_name: pyspark-server
#    networks:
#      - app-tier
